
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      mode: assignment
  template:
    metadata:
      labels:
        mode: assignment
    spec: 
      containers:
      - name: reactapp
        image: shivabogem/testapp
        ports:
        - containerPort: 5000
    
---

apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer
  selector:
    mode: assignment
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
